import { supabase } from "@/lib/supabase";
import QRCode from "qrcode";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * Generates (if absent) a QR-coded PDF permit for an approved application.
 * Returns the inserted permit row.
 */
export async function generatePermitForApplication(applicationId: string) {
  // Load application
  const { data: app, error: appError } = await supabase
    .from("applications")
    .select("id, data, permit_types(name, municipality_id), user_email, status, created_at")
    .eq("id", applicationId)
    .maybeSingle();

  if (appError) throw appError;
  if (!app) throw new Error("Application not found");

  const normalizedStatus = (app.status ?? "").toUpperCase();
  if (!["APPROVED", "DECISION_UPLOADED"].includes(normalizedStatus)) {
    throw new Error("Application not in an approved state");
  }

  // Prevent duplicate generation
  const { data: existing, error: existErr } = await supabase
    .from("permits")
    .select("id")
    .eq("application_id", applicationId)
    .limit(1);
  if (existErr) throw existErr;
  if (existing?.length) return existing[0]; // Already exists

  const municipalityId = app.permit_types?.municipality_id ?? "UNKNOWN";
  const permitType = app.permit_types?.name ?? "UNKNOWN";
  const ownerName =
    app.data?.applicant?.fullName ??
    app.data?.applicant_name ??
    app.data?.fullName ??
    "UNKNOWN OWNER";
  const plotAddress =
    app.data?.applicant?.address ??
    app.data?.address ??
    app.data?.plot ??
    "UNKNOWN ADDRESS";

  const year = new Date().getFullYear();

  // Sequence: count existing permits for municipality-year
  const { data: existingPermits, error: seqErr } = await supabase
    .from("permits")
    .select("permit_id")
    .ilike("permit_id", `HEX-${municipalityId}-${year}-%`);
  if (seqErr) throw seqErr;

  const nextSeq = (existingPermits?.length ?? 0) + 1;
  const padded = String(nextSeq).padStart(5, "0");
  const permit_id = `HEX-${municipalityId}-${year}-${padded}`;

  const qr_url = `https://verify.hex-edge.com/permits/${permit_id}`;

  // QR Code image (data URL)
  const qrDataUrl = await QRCode.toDataURL(qr_url, {
    errorCorrectionLevel: "M",
    margin: 1,
    scale: 6,
  });

  // Create PDF
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const { width } = page.getSize();

  page.drawText("Official Municipal Permit", {
    x: 50,
    y: 780,
    size: 20,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });

  page.drawText(`Permit ID: ${permit_id}`, { x: 50, y: 750, size: 12, font });
  page.drawText(`Permit Type: ${permitType}`, { x: 50, y: 735, size: 12, font });
  page.drawText(`Owner: ${ownerName}`, { x: 50, y: 720, size: 12, font });
  page.drawText(`Plot / Address: ${plotAddress}`, { x: 50, y: 705, size: 12, font });
  page.drawText(`Issued: ${new Date().toLocaleString()}`, { x: 50, y: 690, size: 12, font });
  page.drawText(`Verify: ${qr_url}`, { x: 50, y: 675, size: 10, font, color: rgb(0, 0, 0.6) });

  const qrBytes = dataUrlToBytes(qrDataUrl);
  const qrImage = await pdfDoc.embedPng(qrBytes);
  const qrDim = 150;
  page.drawImage(qrImage, {
    x: width - qrDim - 60,
    y: 660,
    width: qrDim,
    height: qrDim,
  });

  page.drawText(`Municipality: ${municipalityId}`, { x: 50, y: 640, size: 11, font });
  page.drawText("Document hash (SHA-256): <pending>", { x: 50, y: 625, size: 10, font });

  // Footer line
  page.drawLine({
    start: { x: 50, y: 80 },
    end: { x: width - 50, y: 80 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  page.drawText(
    "Generated by Lebanon Digital Permits • Digitally verifiable document",
    { x: 50, y: 65, size: 9, font, color: rgb(0.3, 0.3, 0.3) }
  );

  let pdfBytes = await pdfDoc.save();
  const pdfHash = await sha256Hex(pdfBytes);

  // Inject actual hash
  const pdfDoc2 = await PDFDocument.load(pdfBytes);
  const page2 = pdfDoc2.getPages()[0];
  page2.drawText(`Document hash (SHA-256): ${pdfHash}`, { x: 50, y: 625, size: 10, font });
  pdfBytes = await pdfDoc2.save();

  // Upload to storage
  const s3Key = `permits/${applicationId}/${permit_id}.pdf`;
  const { error: uploadErr } = await supabase.storage
    .from("documents")
    .upload(s3Key, new Blob([pdfBytes], { type: "application/pdf" }), {
      upsert: false,
      cacheControl: "3600",
    });
  if (uploadErr) throw uploadErr;

  // Insert permit row
  const { data: inserted, error: insErr } = await supabase
    .from("permits")
    .insert({
      permit_id,
      application_id: applicationId,
      municipality_id: municipalityId,
      permit_type: permitType,
      owner_name: ownerName,
      plot_address: plotAddress,
      status: "ACTIVE",
      pdf_s3_key: s3Key,
      pdf_sha256: pdfHash,
      qr_url,
      meta: {},
    })
    .select()
    .maybeSingle();
  if (insErr) throw insErr;

  // Audit
  await supabase.from("audit_log").insert({
    application_id: applicationId,
    action: "PERMIT_GENERATED",
    meta: { permit_id, pdf_s3_key: s3Key, pdf_sha256: pdfHash },
  });

  return inserted;
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.split(",")[1];
  const raw = atob(base64);
  const arr = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) arr[i] = raw.charCodeAt(i);
  return arr;
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}