// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Normalize empty env vars (e.g. `VITE_SUPABASE_URL=`) to undefined to avoid hard-crashing at import-time.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim() || undefined;
// Some codepaths (legacy scaffolding) use VITE_SUPABASE_PUBLISHABLE_KEY.
// For this repo, treat it as an alias of the anon/public key.
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  ""
).trim() || undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const SUPABASE_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(
  SUPABASE_URL ?? "http://localhost:54321",
  SUPABASE_PUBLISHABLE_KEY ?? "public-anon-key",
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});